### PR TITLE
DO NOT MERGE: appengine 1.9.70

### PR DESCRIPTION
**Pull request by dragonsinth**
@jhump this is everything on your branch, minus the GAE tag, plus "Absolute path fixup when google module is installed in system".

### CODE REVIEW

**Comment by jhump** [comment]
Is there a reason to omit the tags stuff in `gaego.py`? We're going to need it before we can actually convert the first module to go111.

**Comment by jhump** [comment]
May want to change merge base of this to `base`, so the diff is actually meaningful.

Also, don't forget to look at the directions [here](https://github.com/cowpaths/mn/tree/master/projects/fullstory/etc/appengine) for creating the wonky merge commit, since we do history in this repo kind of funky...

**Comment by dragonsinth** [comment]
> Is there a reason to omit the tags stuff in `gaego.py`? We're going to need it before we can actually convert the first module to go111.

No, but I was going to do it post-merge, since it's new to 1.9.70.

> May want to change merge base of this to `base`, so the diff is actually meaningful.

Oh yeah, done. :)

> Also, don't forget to look at the directions [here](https://github.com/cowpaths/mn/tree/master/projects/fullstory/etc/appengine) for creating the wonky merge commit, since we do history in this repo kind of funky...

I would never! 😂 Thus the "do not merge".

**Comment by dragonsinth** [comment]
@jhump I updated this branch to reference the exact commit I would ff to master if you want to take a final look before I pull the trigger.

Screen Shot 2019-08-08 at 1 23 27 PM

**Comment by jhump** [comment]
LGTM. Ship it!

**Pull request closed without merging**
